#!/bin/bash

BASE=$(pwd)

# Build the core:
cd $BASE/../airbitz-core/deps
touch recipes/abc/abc.recipe
if [ "$1" == "testnet" ]; then
  ./make-testnet abc.build-android-arm abc.build-android-x86
else
  make abc.build-android-arm abc.build-android-x86
fi

# Now build the JNI wrapper:
cd $BASE
./cpabc "$@"
